/**
 * PROJECT EULER
 * Exercise 002
 * Time: 0.00001s
 *
 * Problem:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89,...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * Solution:
 * If we look at the Fibonacci sequence, we can notice the pattern that every third number
 * is even starting at F_3, so if we express F_n in terms of F_(n-3) and F_(n-6), we are left 
 * with a sequence of even numbers that can easily be added into the desired sum. 
 *
 * In order to express F_n in terms of F_(n-3) and F_(n-6), we must arrive at the following:
 * F_n = F_(n-1) + F_(n-2)
 *     = F_(n-2) + F_(n-3) + F_(n-3) + F_(n-4) since F_(n-1) = F_(n-2) + F_(n-3) and F_(n-2) = F_(n-3) + F_(n-4)
 *     = F_(n-3) + F_(n-4) + F_(n-3) + F_(n-3) + F_(n-4)
 *     = 3F_(n-3) + 2F_(n-4)
 *     = 3F_(n-3) + F_(n-4) + F_(n-5) + F_(n-6)
 *     = 4F_(n-3) + F_(n-6) since F_(n-4) + F_(n-5) = F_(n-3)
 *
 * Unlike the brute force solution, which iterates through every number in the fibonacci sequence,
 * this solution only iterates through even numbers in the sequence and adds them to the sum.
 */

#include "helper.h"

/**
 * Returns sum of even-valued terms in the Fibonacci sequence up to limit p
 */
long sumFibonacci(long p)
{
    long fib3 = 2;
    long fib6 = 0;
    long result = 2;
    long sum = 0;

    while (result < p) {
        sum += result;
        result = 4 * fib3 + fib6;
        fib6 = fib3;
        fib3 = result;
    }

    return sum;
}

int main(void)
{
    const long limit = 4000000;

    startTimer();
    long sum = sumFibonacci(limit);
    stopTimer();
    result(sum, 4613732);

    return 0;
}

